<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>WpfBatchDemo</RootNamespace>
    <AssemblyName>WpfBatchDemo</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BatchObservableCollection\BatchObservableCollection.csproj" />
  </ItemGroup>

</Project>
